modLoader="javafml"
loaderVersion="[46,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    displayURL="${mod_homepage}"
    updateJSONURL="${mod_update_json}"
    logoFile="${mod_logo}"
    credits="${mod_credits}"
    authors="${mod_author}"
    description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="journeymap"
    mandatory=true
    versionRange="[1.20.1-5.9.18,)"
    ordering="NONE"
    side="BOTH"
