import com.modrinth.minotaur.dependencies.ModDependency
import com.modrinth.minotaur.dependencies.VersionDependency

plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'idea'
    id 'net.darkhax.curseforgegradle' version '1.+'
    id "com.modrinth.minotaur" version "2.+"
}

base.archivesName = "${project.mod_name}-${project.minecraft_version}"
remapJar.archiveClassifier = "fabric"

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.mappings_mc_version}:${project.mappings_date}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    modImplementation group: 'mysticdrew', name: 'common-networking-fabric', version: project.common_networking_version, changing: true
    modApi include(group: 'mysticdrew', name: 'common-networking-fabric', version: project.common_networking_version, changing: true)
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api_port_version}"
    modApi "com.terraformersmc:modmenu:${project.modmenu_version}"
    modApi group: 'info.journeymap', name: 'journeymap-api-fabric', version: project.journeymap_api_version, changing: true
    modImplementation "curse.maven:journeymap-${project.jm_project_id}:${project.jm_fabric_file_id}"
}

loom {
    def aw = project(":Common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        useLegacyMixinAp = false
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            property("mixin.debug.export", "true")
            ideConfigGenerated(true)
            runDir("runs/client")
            programArg("--username=Dev")
        }
        server {
            server()
            serverWithGui()
            setConfigName("Fabric Server")
            property("mixin.debug.export", "true")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

jar {
    dependsOn "processDocs"
}

tasks.register('processDocs', Copy) {
    // update docs
    from(file("../doc/")) {
        include '*.md'
        expand 'loaderversion': fabric_version,
                'loadername': "Fabric API",
                'journeymap_doc_version': journeymap_doc_version,
                'extra_doc_requirements': "* Forge Config API Port: ${forge_config_api_port_version}\n* Mod Menu (Optional): ${modmenu_version}"
    }
    into 'build/doc'
}

if (!project.hasProperty("curseForgeApiKey")) {
    ext.curseForgeApiKey = project.findProperty("curseforge_api_key") ?: "notset"
}
if (!project.hasProperty("modrinthApiKey")) {
    ext.modrinthApiKey = project.findProperty("modrinth_api_key") ?: "notset"
}

task publishCurseForge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    apiToken = "${curseForgeApiKey}"
    def mainFile = upload(curseforge_project_id, remapJar)
    mainFile.displayName = "${mod_name}-${minecraft_version}-${version}-fabric"
    mainFile.releaseType = release_type
    mainFile.addModLoader("Fabric", "Quilt")
    mainFile.addJavaVersion("Java 21")
    mainFile.addGameVersion("${minecraft_version}")
    mainFile.addEnvironment("Server", "Client")
    mainFile.addRelations("requiredDependency", "fabric-api", "journeymap", "forge-config-api-port")
    mainFile.addRelation("modmenu", "optionalDependency")
    mainFile.changelogType = "markdown"
    mainFile.changelog = file("$project.buildDir/doc/changelog.md")
}

tasks.modrinth.dependsOn(tasks.build)

modrinth {
//    debugMode.set(true)
    token = "${modrinthApiKey}"
    projectId = modrinth_project_id
    versionNumber = "${minecraft_version}-${version}-fabric"
    versionName = "${mod_name}-${minecraft_version}-${version}-fabric"
    versionType = release_type
    uploadFile = remapJar
    gameVersions = ["${minecraft_version}"]
    loaders = ["fabric", "quilt"]
    dependencies = [
            new ModDependency("fabric-api", "required"),
            new VersionDependency("journeymap", "${journeymap_doc_version}+fabric", "required"),
            new VersionDependency("forge-config-api-port", "${forge_config_api_port_version}", "required"),
            new VersionDependency("modmenu", "${modmenu_version}", "optional")
    ]
    changelog = file("$project.buildDir/doc/changelog.md").exists() ? file("$project.buildDir/doc/changelog.md").text : null
}

project.afterEvaluate {
    project.tasks.findAll { task -> (task.name.startsWith('curseforge') || task.name.startsWith('modrinth'))
    }.each {
        projectTask -> projectTask.dependsOn build
    }
}
