import com.modrinth.minotaur.dependencies.ModDependency
import com.modrinth.minotaur.dependencies.VersionDependency
import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id 'idea'
    id 'net.darkhax.curseforgegradle' version '1.1.28'
    id "com.modrinth.minotaur" version "2.9.0"
}

base.archivesName = "${project.mod_name}-${project.minecraft_version}-fabric"

configurations {
    embeddedApi {
        canBeConsumed = false
        canBeResolved = true
        transitive = false
    }
}

dependencies {
    def apiIsSnapshot = project.api_version.endsWith('-SNAPSHOT')

    implementation("${project.api_group}:${project.api_artifact_id}:${project.api_version}") {
        changing = apiIsSnapshot
    }
    embeddedApi("${project.api_group}:${project.api_artifact_id}:${project.api_version}") {
        changing = apiIsSnapshot
    }

    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation 'com.google.code.findbugs:jsr305:3.0.1'

    compileOnly("mysticdrew:common-networking-fabric:${project.common_networking_version}-${project.minecraft_version}") {
        changing = true
        transitive = false
    }
    include(implementation("com.electronwill.night-config:core:${project.nightconfig_version}"))
    include(implementation("com.electronwill.night-config:toml:${project.nightconfig_version}"))
    compileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
    compileOnly("info.journeymap:journeymap-api-fabric:${project.journeymap_api_version}-${project.journeymap_api_mc_version}-SNAPSHOT") {
        changing = true
        transitive = false
    }
    compileOnly "curse.maven:journeymap-${project.jm_project_id}:${project.jm_fabric_file_id}"
    runtimeOnly "curse.maven:journeymap-${project.jm_project_id}:${project.jm_fabric_file_id}"
}

loom {
    def aw = project(":Common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        useLegacyMixinAp = false
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            property("mixin.debug.export", "true")
            ideConfigGenerated(true)
            runDir("runs/client")
            programArg("--username=Dev")
        }
        server {
            server()
            setConfigName("Fabric Server")
            property("mixin.debug.export", "true")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

idea {
    module {
        excludeDirs += file('runs')
    }
}

jar {
    dependsOn "processDocs"
    from({
        configurations.embeddedApi.collect { zipTree(it) }
    }) {
        exclude 'META-INF/MANIFEST.MF'
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
    }
}


registerProcessDocsTask(
        "Fabric API",
        fabric_api_version,
        "* Mod Menu (Optional): ${modmenu_version}"
)

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    apiToken = "${curseForgeApiKey}"
    def mainFile = upload(curseforge_project_id, jar)
    mainFile.displayName = "${minecraft_version}-${version}-fabric"
    mainFile.releaseType = release_type
    mainFile.addModLoader("Fabric", "Quilt")
    mainFile.addJavaVersion("Java 25")
    mainFile.addGameVersion("${minecraft_version}")
    mainFile.addEnvironment("Server", "Client")
    mainFile.addRelations("requiredDependency", "fabric-api", "journeymap")
    mainFile.addRelation("modmenu", "optionalDependency")
    mainFile.changelogType = "markdown"
    mainFile.changelog = file("$project.buildDir/doc/changelog.md")
}

modrinth {
//    debugMode.set(true)
    token = "${modrinthApiKey}"
    projectId = modrinth_project_id
    versionNumber = "${minecraft_version}-${version}-fabric"
    versionName = "${mod_name}-${minecraft_version}-${version}-fabric"
    versionType = release_type
    uploadFile = jar
    gameVersions = ["${minecraft_version}"]
    loaders = ["fabric", "quilt"]
    dependencies = [
            new ModDependency("fabric-api", "required"),
            new VersionDependency("journeymap", "${journeymap_doc_version}+fabric", "required"),
            new VersionDependency("modmenu", "${modmenu_version}", "optional")
    ]
    changelog.set(providers.provider {
        file("$project.buildDir/doc/changelog.md").text
    })
}
