# Project
version=3.0.0-beta.10
release_type=beta
group=games.alejandrocoria.mapfrontiers
java_version=21

api_version=0.1.0-SNAPSHOT
api_group=games.alejandrocoria
api_artifact_id=mapfrontiers-api

# Common
minecraft_version=1.21.10
minecraft_version_range=[1.21.10, 1.22)

#mappings
mappings_mc_version=1.21.9
mappings_date=2025.10.05

neo_form_version=1.21.10-20251007.142004

# Mod options
mod_name=MapFrontiers
mod_author=Alejandro Coria (MemeSapiens)
mod_id=mapfrontiers
mod_description=This mod is an addon for Journey Map that allows you to divide the map into regions and assign them names and colors.
mod_email=contact@alejandrocoria.games
mod_homepage=https://alejandrocoria.games/projects/MapFrontiers/
mod_issues=https://github.com/alejandrocoria/MapFrontiers/issues
mod_sources=https://github.com/alejandrocoria/MapFrontiers
mod_credits=By Alejandro Coria. Many thanks to the JourneyMap team.
mod_license=MIT
mod_logo=logo.png

curseforge_project_id=366783
modrinth_project_id=hWlsli6y

# Fabric
fabric_version=0.134.1+1.21.10
fabric_loader_version=0.17.2

# Forge
forge_version=1.21.10-60.0.15
forge_loader_version_range=[60,)

# NeoForge
neoforge_version=21.10.40-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

# Dependencies
jm_project_id=32274
jm_forge_file_id=7630645
jm_fabric_file_id=7630646
jm_neoforge_file_id=7630647
journeymap_doc_version=1.21.10-6.0.0-beta.58
journeymap_api_version=2.0.0-1.21.10-SNAPSHOT
journeymap_version_range=[1.21.10-6.0.0-beta.58,)
journeymap_min_version=1.21.10-6.0.0-beta.58

common_networking_version=1.0.22-1.21.10

# Keep this aligned with the NightConfig version bundled by Forge.
nightconfig_version=3.7.4

modmenu_version=16.0.1
