# Project
version=3.0.0-beta.9
release_type=beta
group=games.alejandrocoria.mapfrontiers
java_version=25

api_version=0.1.0-SNAPSHOT
api_group=games.alejandrocoria
api_artifact_id=mapfrontiers-api

# Common
minecraft_version=26.1.2
minecraft_version_range=[26.1.2, 27)

#mappings
mappings_mc_version=26.1
mappings_date=2025.12.20

neo_form_version=26.1.2-1

# Mod options
mod_name=MapFrontiers
mod_author=Alejandro Coria (MemeSapiens)
mod_id=mapfrontiers
mod_description=This mod is an addon for Journey Map that allows you to divide the map into regions and assign them names and colors.
mod_email=contact@alejandrocoria.games
mod_homepage=https://alejandrocoria.games/projects/MapFrontiers/
mod_issues=https://github.com/alejandrocoria/MapFrontiers/issues
mod_sources=https://github.com/alejandrocoria/MapFrontiers
mod_credits=By Alejandro Coria. Many thanks to the JourneyMap team.
mod_license=MIT
mod_logo=logo.png

curseforge_project_id=366783
modrinth_project_id=hWlsli6y

# Fabric
fabric_api_version=0.146.1+26.1.2
fabric_loader_version=0.19.2

# Forge
forge_version=64.0.4
forge_loader_version_range=[64,)

# NeoForge
neoforge_version=26.1.2.22-beta
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

# Dependencies
jm_project_id=32274
jm_forge_file_id=8325544
jm_fabric_file_id=8325543
jm_neoforge_file_id=8325545
journeymap_doc_version=26.1.2-6.0.0
journeymap_api_version=2.0.0
journeymap_api_mc_version=26.1
journeymap_version_range=[26.1.2-6.0.0,)
journeymap_min_version=26.1.2-6.0.0

common_networking_version=1.0.23

# Keep this aligned with the NightConfig version bundled by Forge.
nightconfig_version=3.7.4

modmenu_version=18.0.0-beta.1
