# Project
version=2.7.0-beta.17
release_type=beta
group=games.alejandrocoria.mapfrontiers
java_version=21

# Common
minecraft_version=1.21.7
minecraft_version_range=[1.21.7, 1.22)

#mappings
parchment_minecraft=1.21.5
parchment_version=2025.04.19

#parchement_mappings_date
mappings_date=2025.04.19

neo_form_version=1.21.7-20250630.141722

# Mod options
mod_name=MapFrontiers
mod_author=Alejandro Coria (MemeSapiens)
mod_id=mapfrontiers
mod_description=This mod is an addon for Journey Map that allows you to divide the map into regions and assign them names and colors.
mod_email=contact@alejandrocoria.games
mod_homepage=https://alejandrocoria.games/projects/MapFrontiers/
mod_issues=https://github.com/alejandrocoria/MapFrontiers/issues
mod_sources=https://github.com/alejandrocoria/MapFrontiers
mod_update_json=https://alejandrocoria.games/projects/MapFrontiers/update.json
mod_credits=By Alejandro Coria. Many thanks to the JourneyMap team.
mod_license=MIT
mod_logo=logo.png

curseforge_project_id=366783
modrinth_project_id=hWlsli6y

# Forge
forge_version=1.21.7-57.0.0
forge_loader_version_range=[55,)

# Fabric
fabric_version=0.128.1+1.21.7
fabric_loader_version=0.16.14

# NeoForge
neoforge_version=21.7.1-beta
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
jm_project_id=32274
jm_forge_file_id=6730471
jm_fabric_file_id=6730472
jm_neoforge_file_id=6730473
journeymap_doc_version=1.21.7-6.0.0-beta.53
journeymap_api_version=2.0.0-1.21.6-SNAPSHOT
journeymap_version_range=[1.21-5.9.20,)
journeymap_min_version=1.21-5.9.20

common_networking_jarjar_version=[1.0.21, 5.0.0)
common_networking_version=1.0.21-1.21.7

forge_config_api_port_version=21.7.0
forge_config_api_port_version_range=[21.7.0,)

modmenu_version=15.0.0-beta.2
