plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

tasks.processResources {
    from(rootProject.file('LICENSE'))
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

dependencies {
    def apiIsSnapshot = project.api_version.endsWith('-SNAPSHOT')

    api("${project.api_group}:${project.api_artifact_id}:${project.api_version}") {
        changing = apiIsSnapshot
    }
    compileOnly 'org.spongepowered:mixin:0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly 'io.github.llamalad7:mixinextras-common:0.3.5'
    annotationProcessor 'io.github.llamalad7:mixinextras-common:0.3.5'

    compileOnly "mysticdrew:common-networking-common:${project.common_networking_version}-${project.minecraft_version}"
    api "com.electronwill.night-config:core:${project.nightconfig_version}"
    api "com.electronwill.night-config:toml:${project.nightconfig_version}"
    compileOnly("info.journeymap:journeymap-api-common:${project.journeymap_api_version}-${project.journeymap_api_mc_version}-SNAPSHOT") {
        changing = true
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
