modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    displayURL="${mod_homepage}"
    updateJSONURL="${mod_update_json}"
    logoFile="${mod_logo}"
    credits="${mod_credits}"
    authors="${mod_author}"
    description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="journeymap"
    type="required"
    versionRange="[1.20.4-5.9.20,)"
    ordering="NONE"
    side="BOTH"
