import com.modrinth.minotaur.dependencies.VersionDependency
import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'idea'
    id 'net.darkhax.curseforgegradle' version '1.1.28'
    id "com.modrinth.minotaur" version "2.9.0"
}

base.archivesName = "${project.mod_name}-${project.minecraft_version}-neoforge"

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':Common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = mappings_mc_version
        mappingsVersion = mappings_date
    }
    runs {
        configureEach {
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
        server {
            server()
            gameDirectory = project.file('runs/server')
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    dependencies {
        implementation project(':Api')
        implementation "mysticdrew:common-networking-neoforge:${project.common_networking_version}"
        implementation "com.electronwill.night-config:core:${project.nightconfig_version}"
        implementation "com.electronwill.night-config:toml:${project.nightconfig_version}"
        jarJar "com.electronwill.night-config:core:${project.nightconfig_version}"
        jarJar "com.electronwill.night-config:toml:${project.nightconfig_version}"
        api("info.journeymap:journeymap-api-neoforge:${project.journeymap_api_version}") {
            changing = true
        }
        implementation "curse.maven:journeymap-${project.jm_project_id}:${project.jm_neoforge_file_id}"
    }
}

idea {
    module {
        excludeDirs += file('runs')
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

jar {
    dependsOn "processDocs"
    dependsOn project(':Api').tasks.named('classes')
    from project(':Api').sourceSets.main.output
}

registerProcessDocsTask(
        "NeoForge",
        neoforge_version,
        ""
)

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    apiToken = "${curseForgeApiKey}"
    def mainFile = upload(curseforge_project_id, jar)
    mainFile.displayName = "${minecraft_version}-${version}-neoforge"
    mainFile.releaseType = release_type
    mainFile.addModLoader("NeoForge")
    mainFile.addJavaVersion("Java 21")
    mainFile.addGameVersion("${minecraft_version}")
    mainFile.addEnvironment("Server", "Client")
    mainFile.addRelations("requiredDependency", "journeymap")
    mainFile.addRelation("modmenu", "optionalDependency")
    mainFile.changelogType = "markdown"
    mainFile.changelog = file("$project.buildDir/doc/changelog.md")
}

modrinth {
//    debugMode.set(true)
    token = "${modrinthApiKey}"
    projectId = modrinth_project_id
    versionNumber = "${minecraft_version}-${version}-neoforge"
    versionName = "${mod_name}-${minecraft_version}-${version}-neoforge"
    versionType = release_type
    uploadFile = jar
    gameVersions = ["${minecraft_version}"]
    loaders = ["neoforge"]
    dependencies = [
            new VersionDependency("journeymap", "${journeymap_doc_version}+neoforge", "required"),
    ]
    changelog = file("$project.buildDir/doc/changelog.md").exists() ? file("$project.buildDir/doc/changelog.md").text : null
}
