package games.alejandrocoria.mapfrontiers.api.model;

public enum FrontierVisibilityFlag {
    Frontier,
    AnnounceInChat,
    AnnounceInTitle,
    Fullscreen,
    FullscreenName,
    FullscreenOwner,
    FullscreenBanner,
    FullscreenDay,
    FullscreenNight,
    FullscreenUnderground,
    FullscreenTopo,
    FullscreenBiome,
    Minimap,
    MinimapName,
    MinimapOwner,
    MinimapBanner,
    MinimapDay,
    MinimapNight,
    MinimapUnderground,
    MinimapTopo,
    MinimapBiome,
    Webmap,
    WebmapName,
    WebmapOwner,
    WebmapBanner,
    WebmapDay,
    WebmapNight,
    WebmapUnderground,
    WebmapTopo,
    WebmapBiome
}
