plugins {
    id 'java-library'
    id 'maven-publish'
    id "com.modrinth.minotaur" version "2.9.0"
}

group = "games.alejandrocoria"
version = project.api_version

base {
    archivesName = "mapfrontiers-api"
}

repositories {
    mavenCentral()
}

java {
    withSourcesJar()
    withJavadocJar()
}

dependencies {
    implementation 'org.apache.logging.log4j:log4j-api:2.24.1'
}

tasks.processResources {
    from(rootProject.file('LICENSE'))
}

if (!project.hasProperty("modrinthApiKey")) {
    ext.modrinthApiKey = project.findProperty("modrinth_api_key") ?: "notset"
}

tasks.modrinth.dependsOn(tasks.build)

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group.toString()
            artifactId = base.archivesName.get()
            version = project.version.toString()
        }
    }
}

modrinth {
    debugMode.set(true)
    token = "${modrinthApiKey}"
    projectId = api_modrinth_project_id
    versionNumber = "${api_version}"
    versionName = "${mod_name}-API-${api_version}"
    versionType = api_release_type
    detectLoaders = false
    uploadFile = jar
    gameVersions = ["${minecraft_version}"]
    loaders = ["java-agent"]
    additionalFiles {
        sourcesJar(tasks.named('sourcesJar'))
        javadocJar(tasks.named('javadocJar'))
    }
}
